name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_VERSION: 16
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run type checks
        run: npm run typecheck

      - name: Deploy to Fly.io
        if: github.ref == 'refs/heads/main'
        uses: superfly/flyctl-actions@1.1
        with:
          args: 'deploy'
